### PR TITLE
Formate the code

### PR DESCRIPTION
**Pull request by MoulatiMehdi**
1- i just format the code , i didn't touch the preamble. 
2- for readme.md i just change typsetting to typesetting
3- unit circle of snow works for me

### CODE REVIEW

**Comment by MoulatiMehdi** [comment]
unit circle of snow  works for me

**Comment by riemann-discord** [comment]
Original `sohcatoa` on top. new formatted `sohcahtoa` on bottom

Screen Shot 2023-02-06 at 10 31 26 AM

For some reason, the newly formatted `sohcahtoa` factoid puts the triangle on a new line instead of to the right of the definitions. Do you think you could investigate why?

**Comment by MoulatiMehdi** [comment]
i will try

**Comment by MoulatiMehdi** [comment]
fixed, it's was just a new line between two enviroments

**Review by riemann-discord — APPROVED** [review]

**Comment by riemann-discord** [comment]
Thanks!

**Comment by MoulatiMehdi** [comment]
anytime

**Pull request merged**
